### ISSUE TITLE
Mobile-friendly design?

### ISSUE THREAD

**Issue by mcchrish** [twilio/twilio-video-diagnostics-react-app#23]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/7200153/146319219-4e46ebda-bb59-406a-8641-49970123f9ed.png">

**Comment by olipyskoty** [comment]
Hey @mcchrish, thanks so much for the issue report 😅 !

We are currently in the process of adding mobile support for this app. It should be ready to go some time next year, and we will let you know as soon as that happens. 

Thank you!

**Comment by theHilikus** [comment]
That's great to hear. In the meantime, is there an equivalent app for android? any way to run tests from an android device at all?

**Comment by olipyskoty** [comment]
Hey @theHilikus thanks for the question! 

As of now there is no Twilio Video Diagnostics app for android or iOS. This app can only be used via web browser (either on your desktop or mobile device when we implement the designs). 

That being said, once we have the mobile designs in place for this app, users should be able to run these tests on an android device using any of the [supported browsers](https://www.twilio.com/docs/video/javascript#supported-browsers). 

It is on our roadmap to implement mobile designs in the new year, so stay tuned!

Thank you and happy new year!

**Comment by olipyskoty** [comment]
Hey @mcchrish and @theHilikus thank you for your patience!

Mobile support is finally available for the Video Diagnostics Application! 🎉  As long as users are accessing the application through any of our [supported browsers](https://www.twilio.com/docs/video/javascript#supported-browsers), they should be able to successfully view and run the tests as they would via desktop.

Please let us know if you have any questions or run into any issues. Thanks again!
