### ISSUE TITLE
Would this project be good for diagnosing in mobile apps?

### ISSUE THREAD

**Issue by sevgit** [twilio/twilio-video-diagnostics-react-app#42]
Hey there, first of all I would like to thank you for creating this project. 

I'm part of a telemedicine company that has native iOS and Android apps, and we were wondering whether using this diagnostics tool would be a good approach for those apps. If not, is there any similar tool that can be easily embedded on Android and iOS?

Cheers!

**Comment by olipyskoty** [comment]
Hey @sevgit, thanks for reaching out! 

We do not believe that Twilio has anything like this app for iOS and Android at the moment unfortunately. 

This Video Diagnostics App could be used for iOS/Android users to test connectivity with Twilio's servers, and their network qualities, but all of the device related tests will most likely not be as helpful as they are primarily used to make sure that a user has the correct browser permissions in place. 

Hope that helps and have a great weekend!
