### ISSUE TITLE
Email authentication required to run Diagnostics

### ISSUE THREAD

**Issue by akhilvarmabyjus** [twilio/twilio-video-diagnostics-react-app#55]
Hi, 

Our users have been using the Twilio Video Diagnostics app to do a system check before a live class. The new change which requires email authentication is a blocker for the students as most of them use their parents' laptops and don't have access to their parent's email.

Is there anything we can do to bypass the email auth?

Thank You
<img width="1440" alt="Screenshot 2022-07-04 at 11 32 44 AM" src="https://user-images.githubusercontent.com/108651178/177091208-77db41d5-aff0-45cd-9c2e-ae19b21a3d73.png">

**Comment by olipyskoty** [comment]
Hey @akhilvarmabyjus thanks for the question!

Looks like you're using the Video Diagnostics App that is hosted by Twilio (https://video-diagnostics.twilio.com). Unfortunately, there is no way to bypass the email authentication as this is a crucial step to preventing any malicious behavior. 

However, you can easily clone _this_ repo and [deploy the code](https://github.com/twilio/twilio-video-diagnostics-react-app/blob/v1.1.0/README.md#deploy-the-app) to Twilio Serverless. This will give you a URL to a fully functional app without any email authentication. You can also host this application using a third party service (i.e. Heroku, Google Cloud) if you choose to deploy the application that way. Please check out the information about the [token server](https://github.com/twilio/twilio-video-diagnostics-react-app/blob/v1.1.0/README.md#deploy-the-app) from our README.

Thank you!
